name: Client

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/Docs/**'
      - '.github/workflows/Docs.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 9.0.101

      - name: Install Tools
        run: dotnet tool restore

      - name: RunTests
        run: dotnet run ExecuteTests

      - name: Build
        run: dotnet run publishDocs

      - name: Publish Docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: publish/docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: docs
          path: docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
